site_name: Testcontainers Native
site_description: >-
  Testcontainers for C/C++/Swift and other native projects.
  It is not a standalone Testcontainers engine,
  but a shared bridge library and language-specific adapters.
  The project is based on Testcontainers for Go which is one of the most powerful Testcontainers implementations.
copyright: >-
  Copyright &copy; 2024 - Oleg Nenashev and all contributors.
repo_url: https://github.com/testcontainers/testcontainers-native
repo_name: GitHub Repo
edit_uri: edit/main/
site_url: https://testcontainers.github.io/testcontainers-native

# Build
site_dir: _site
docs_dir: .
exclude_docs: |
  /_deps/**
  !.devcontainer
  /build/_deps/**

nav:
  - Documentation:
    - Overview: README.md
    - Getting Started: docs/getting-started.md
    - Under the Hood: docs/architecture/README.md
    - Usage in C: docs/c/README.md
    - Usage in C++: docs/cpp/README.md
    - Usage in Swift: docs/swift/README.md
    - Demos:
      - All Demos: demo/README.md
      - Generic Container: demo/generic-container/README.md  
      - WireMock Module: demo/wiremock/README.md
  - Modules:
    - Overview: modules/README.md
    - Embedded Modules:
      - WireMock: modules/wiremock/README.md
  - Contributing: CONTRIBUTING.md
  - Resources:
    - Release Notes: docs/changelog.md
    - Roadmap: ROADMAP.md
    - Support: docs/SUPPORT.md
    - Security: docs/SECURITY.md

plugins:
  - search
  - autorefs
  - macros:
      include_dir: .
      on_error_fail: true
      on_undefined: strict
  - mkdocs-pdf
  - social
  - same-dir
  - redirects:
      redirect_maps:
  - mkdocstrings:
      default_handler: python
      enable_inventory: true
      handlers:
        python:
          paths: [src]
  - mkdocs_github_changelog:
      token: !ENV GITHUB_TOKEN
      base_indent: 2
      autoprocess: true
      enabled: true

# Markdown
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: '#'
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Theme
theme:
  name: material
  highlightjs: true
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    # NOT compatible qith toc.integrate
    # - navigation.indexes
    - navigation.path
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  font:
    text: DM Sans
    code: Roboto Mono
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  favicon: docs/images/logo/logo_testcontainers_c_square.png
  logo: docs/images/logo/logo_testcontainers_c_square.png
  icon:
    repo: fontawesome/brands/github
 
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/testcontainers/testcontainers-native
      name: GitHub
    - icon: fontawesome/brands/slack
      link: http://slack.testcontainers.org/
      name: Slack
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/testcontainers
      name: Twitter
